// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIaxScBr3Jzh0voiDYxtGuAP2ZoNLpDYk',
    appId: '1:685301090571:web:a3cc6a25b51ab6b132ba0e',
    messagingSenderId: '685301090571',
    projectId: 'taskschedular-56db9',
    authDomain: 'taskschedular-56db9.firebaseapp.com',
    storageBucket: 'taskschedular-56db9.appspot.com',
    measurementId: 'G-P4T35P6BW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkIFuDSIZ75-aauUchxzL4R_EVJrz3xpA',
    appId: '1:685301090571:android:f236a2e53fd0558b32ba0e',
    messagingSenderId: '685301090571',
    projectId: 'taskschedular-56db9',
    storageBucket: 'taskschedular-56db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OPlEv7bwUKWL5-mai1_fqj7f1fxJG4I',
    appId: '1:685301090571:ios:62f4032f197ba71132ba0e',
    messagingSenderId: '685301090571',
    projectId: 'taskschedular-56db9',
    storageBucket: 'taskschedular-56db9.appspot.com',
    iosBundleId: 'com.example.taskschedular',
  );
}
